EmployeesTasks/EmployeesTasks/Controllers/EmployeeController/EmployeesController.cs
using EmployeesTasks.Service.Services.Contracts;
using EmployeesTasks.ViewModels.Employees;
using EmployeesTasks.ViewModels.Mappers;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeesTasks.Controllers.EmployeeController
{
	public class EmployeesController : Controller
	{
		private readonly IEmployeeService _employeeService;

		public EmployeesController(IEmployeeService employeeService)
		{
			_employeeService = employeeService;
		}

		public async Task<IActionResult> Index(int employeePage = 1)
		{
			var employees = await _employeeService.GetAllAsync();

			var employeesToShow = employees.Select(m => m.ToViewModel()).ToPagedList(employeePage, 10);

			var resolute = new EmployeesViewModel()
			{
				Employees = employeesToShow
			};

			return View(resolute);
		}

        public async Task<IActionResult> TopEmployees()
        {
            var topEmployees = await _employeeService.GetTopEmployeesAsync();

			var topEmployeesToShow = topEmployees.Select(m => m.ToViewModel()).ToList();

            return View(topEmployeesToShow);
        }
    }
}

EmployeesTasks/EmployeesTasks/Controllers/EmployeeTaskController/EmployeeTasksController.cs
using EmployeesTasks.Service.Services.Contracts;
using EmployeesTasks.ViewModels.EmployeeTasks;
using EmployeesTasks.ViewModels.Mappers;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeesTasks.Controllers.EmployeeTaskController
{
	public class EmployeeTasksController : Controller
	{
		private readonly IEmployeeTaskService _employeeTaskService;

		public EmployeeTasksController(IEmployeeTaskService employeeTaskService)
		{
			_employeeTaskService = employeeTaskService;
		}

		public async Task<IActionResult> Index(int taskPage = 1)
		{
			var tasks = await _employeeTaskService.GetAllAsync();

			var tasksToShow = tasks.Select(m => m.ToViewModel()).ToPagedList(taskPage, 10);

			var resolute = new EmployeeTasksViewModel()
			{
				Tasks = tasksToShow
			};

			return View(resolute);
		}
	}
}

EmployeesTasks/EmployeesTasks/Views/Shared/_HeaderPartial.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Employees" asp-action="Index">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="EmployeeTasks" asp-action="Index">Tasks</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

EmployeesTasks/EmployeesTasks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeesTasks</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    @await Html.PartialAsync("_HeaderPartial")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/EmployeePagination.js"></script>
    <script src="~/js/EmployeeTaskPagination.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>