EmployeesTasks/EmployeesTasks/ViewModels/EmployeeTasks/EmployeeTaskViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace EmployeesTasks.ViewModels.EmployeeTasks
{
    public class EmployeeTaskViewModel
	{
		public int Id { get; set; }

        public int? EmployeeId { get; set; }

        [Required(ErrorMessage = "The Title field is required.")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "The Title length must be between 3 and 30.")]
        public string Title { get; set; }


        [Required(ErrorMessage = "The Name field is required.")]
        [StringLength(200, MinimumLength = 15, ErrorMessage = "The Description length must be between 15 and 200.")]
        public string Description { get; set; }


        [Required(ErrorMessage = "The Deadline field is required.")]
        public DateTime DueDate { get; set; }

		public bool IsDone { get; set; }
	}
}

EmployeesTasks/EmployeesTasks/ViewModels/EmployeeTasks/EmployeeTasksViewModel.cs
using System.Collections.Generic;

namespace EmployeesTasks.ViewModels.EmployeeTasks
{
	public class EmployeeTasksViewModel
	{
		public IEnumerable<EmployeeTaskViewModel> Tasks { get; set; } = new List<EmployeeTaskViewModel>();
	}
}

EmployeesTasks/EmployeesTasks/Controllers/EmployeeController/EmployeeController.cs
using EmployeesTasks.Service.Exceptions;
using EmployeesTasks.Service.Services.Contracts;
using EmployeesTasks.ViewModels.Employees;
using EmployeesTasks.ViewModels.Mappers;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EmployeesTasks.Controllers.EmployeeController
{
	public class EmployeeController : Controller
	{
		private readonly IEmployeeService _employeeService;

		public EmployeeController(IEmployeeService employeeService)
		{
			_employeeService = employeeService;
		}

		public async Task<IActionResult> Create()
		{
			return View("Create");
		}

		[HttpPost]
		public async Task<IActionResult> Create(EmployeeViewModel employeeModel)
		{
			if (!ModelState.IsValid)
			{
				return View("Create", employeeModel);
			}

			var employee = employeeModel.ToDTO();
			await _employeeService.CreateEmployeeAsync(employee);

			return RedirectToAction("Index", "Employees");
		}

		public async Task<IActionResult> Edit(int id)
		{
			try
			{
                var employee = await _employeeService.GetByIdAsync(id);
                return View(employee.ToViewModel());
            }
			catch (EntityNotFoundException)
			{
				return View("Error");
			}
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EmployeeViewModel employeeModel)
		{
            if (!ModelState.IsValid)
            {
                return View("Edit", employeeModel);
            }

            var employee = employeeModel.ToDTO();
			await _employeeService.UpdateEmployeeAsync(employee);

			return RedirectToAction("Index", "Employees");
		}

		public async Task<IActionResult> Details(int id)
		{
			try
			{
                var employee = await _employeeService.GetByIdAsync(id);
                return View(employee.ToViewModel());
            }
            catch (EntityNotFoundException)
            {

                return View("Error");
            }
        }


		[HttpPost]
		public async Task<IActionResult> Delete(int id)
		{
			await _employeeService.DeleteAsync(id);

			return RedirectToAction("Index", "Employees");
		}
	}
}

EmployeesTasks/EmployeesTasks/Controllers/EmployeeTaskController/EmployeeTaskController.cs
using EmployeesTasks.Service.Exceptions;
using EmployeesTasks.Service.Services.Contracts;
using EmployeesTasks.ViewModels.EmployeeTasks;
using EmployeesTasks.ViewModels.Mappers;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeesTasks.Controllers.EmployeeTaskController
{
	public class EmployeeTaskController : Controller
	{
		private readonly IEmployeeTaskService _employeeTaskService;
		private readonly IEmployeeService _employeeService;

		public EmployeeTaskController(IEmployeeTaskService employeeTaskService, IEmployeeService employeeService)
		{
			_employeeTaskService = employeeTaskService;
			_employeeService = employeeService;

        }

		public async Task<IActionResult> Create()
		{
			return View("Create");
		}

		[HttpPost]
		public async Task<IActionResult> Create(EmployeeTaskViewModel taskModel)
		{
			if (!ModelState.IsValid)
			{
				return View("Create", taskModel);
			}

			var task = taskModel.ToDTO();
			await _employeeTaskService.CreateTaskAsync(task);

			return RedirectToAction("Index", "EmployeeTasks");
		}

		public async Task<IActionResult> Edit(int id)
		{
			try
			{
                var task = await _employeeTaskService.GetByIdAsync(id);
                return View(task.ToViewModel());
            }
            catch (EntityNotFoundException)
            {
                return View("Error");
            }
		}

		[HttpPost]
		public async Task<IActionResult> Edit(EmployeeTaskViewModel taskModel)
		{
			var task = taskModel.ToDTO();
			await _employeeTaskService.UpdateTaskAsync(task);

			return RedirectToAction("Index", "EmployeeTasks");
		}

		public async Task<IActionResult> Details(int id)
		{
			try
			{
                var task = await _employeeTaskService.GetByIdAsync(id);
                return View(task.ToViewModel());
            }
			catch (EntityNotFoundException)
			{

                return View("Error");
            }
		}


		[HttpPost]
		public async Task<IActionResult> Delete(int id)
		{
			await _employeeTaskService.DeleteAsync(id);

			return RedirectToAction("Index", "EmployeeTasks");
		}

		public async Task<IActionResult> AssignTask(int id)
		{
            var employees = await _employeeService.GetAllAsync();
            var task = await _employeeTaskService.GetByIdAsync(id);

            var employeesToShow = employees.Select(m => m.ToViewModel()).ToList();

            return View(employeesToShow);
        }

		[HttpPost]
		public async Task<IActionResult> AssignTask(int id, int employeeId)
		{
            var employee = await _employeeService.GetByIdAsync(employeeId);

            await _employeeTaskService.AssignTask(id, employee.Id);

            return RedirectToAction("Index", "EmployeeTasks");
        }

		[HttpPost]
		public async Task<IActionResult> CompleteTask(int id)
		{
			await _employeeTaskService.CompleteTask(id);

			return RedirectToAction("Index", "EmployeeTasks");
		}
	}
}

EmployeesTasks/EmployeesTasks/Controllers/EmployeeTaskController/EmployeeTasksController.cs
using EmployeesTasks.Service.Services.Contracts;
using EmployeesTasks.ViewModels.EmployeeTasks;
using EmployeesTasks.ViewModels.Mappers;
using Microsoft.AspNetCore.Mvc;
using PagedList;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeesTasks.Controllers.EmployeeTaskController
{
	public class EmployeeTasksController : Controller
	{
		private readonly IEmployeeTaskService _employeeTaskService;

		public EmployeeTasksController(IEmployeeTaskService employeeTaskService)
		{
			_employeeTaskService = employeeTaskService;
		}

		public async Task<IActionResult> Index(int taskPage = 1)
		{
			var tasks = await _employeeTaskService.GetAllAsync();

			var tasksToShow = tasks.Select(m => m.ToViewModel()).ToPagedList(taskPage, 10);

			var resolute = new EmployeeTasksViewModel()
			{
				Tasks = tasksToShow
			};

			return View(resolute);
		}
	}
}

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/AssignTask.cshtml
@using EmployeesTasks.ViewModels.Employees
@model List<EmployeeViewModel>

@if (Model.Any())
{
	<table class="table">
		<thead class="thead-light">
			<tr>
				<th scope="col">Name</th>
				<th scope="col"></th>
			</tr>
		</thead>
		<tbody>
			@foreach (var employee in Model)
			{
				<tr>
					<td>@employee.FullName</td>
					<td>
						<form method="post" asp-controller="EmployeeTask" asp-action="AssignTask">
							<input type="hidden" name="employeeId" value="@employee.Id" />
							<button type="submit" class="btn btn-primary">Assign</button>
						</form>
					</td>
				</tr>
			}
		</tbody>
	</table>
}
else
{
	<h2 style="text-align:center">There's no employees yet.</h2>
	<a asp-controller="Employee" asp-action="Create" type="button" class="btn btn-success">Create</a>
}

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/CompleteTask.cshtml
@using EmployeesTasks.ViewModels.EmployeeTasks
@model EmployeeTaskViewModel

<div class="modal fade" id="CompleteTask-@Model.Id" aria-labelledby="CompleteTaskLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="CompleteTaskkLabel"></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form asp-controller="EmployeeTask" asp-action="CompleteTask" method="post">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<input type="hidden" asp-for="Id" />
						<p>Mark task: @Model.Title as completed ?</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-danger">Submit</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/Create.cshtml
@using EmployeesTasks.ViewModels.EmployeeTasks
@model EmployeeTaskViewModel

<form asp-controller="EmployeeTask" asp-action="Create" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DueDate" class="control-label">Deadline</label>
        <input asp-for="DueDate" type="date" class="form-control text-muted"
               min="@DateTime.Now.ToString("yyyy-MM-dd")">
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/Delete.cshtml
@using EmployeesTasks.ViewModels.EmployeeTasks
@model EmployeeTaskViewModel

<div class="modal fade" id="DeleteTask-@Model.Id" aria-labelledby="DeleteTaskLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="DeleteTaskLabel"></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form asp-controller="EmployeeTask" asp-action="Delete" method="post">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>
					<div class="form-group">
						<input type="hidden" asp-for="Id" />
						<p>Are you sure you want to delete @Model.Title ?</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<button type="submit" class="btn btn-danger">Delete</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/Details.cshtml
@using EmployeesTasks.ViewModels.EmployeeTasks
@model EmployeeTaskViewModel

<form>
	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Title:</label>
		<div class="col-sm-10">
			<input type="text" readonly class="form-control-plaintext" asp-for="@Model.Title">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Deadline:</label>
		<div class="col-sm-10">
			<input type="text" readonly class="form-control-plaintext" asp-for="@Model.DueDate" value="@Model.DueDate.ToString("dd/MM/yyyy")">
		</div>
	</div>
	<div class="form-group row">
		<label class="col-sm-2 col-form-label">Assigned Employee ID:</label>
		<div class="col-sm-10">
			@if (Model.EmployeeId == null)
			{
				<input type="text" readonly class="form-control-plaintext" value="Not Assigned">
			}
			else
			{
				<input type="text" readonly class="form-control-plaintext" asp-for="@Model.EmployeeId" value="@Model.EmployeeId">
			}
		</div>
	</div>
	<div class="form-group">
		<label>Description:</label>
		<textarea readonly class="form-control" asp-for="@Model.Description" rows="3"></textarea>
	</div>
	<a asp-controller="EmployeeTask" asp-action="AssignTask" asp-route-id="@Model.Id" type="button" class="btn btn-success">Assign</a>
</form>

EmployeesTasks/EmployeesTasks/Views/EmployeeTask/Edit.cshtml
@using EmployeesTasks.ViewModels.EmployeeTasks
@model EmployeeTaskViewModel

<form asp-controller="EmployeeTask" asp-action="Edit" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DueDate" class="control-label">Deadline</label>
        <input asp-for="DueDate" type="date" class="form-control text-muted"
               min="@DateTime.Now.ToString("yyyy-MM-dd")">
        <span asp-validation-for="DueDate" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>